#!/bin/bash
set -e
set -x
#export PX4_HOME_LAT=39.328166
#export PX4_HOME_LON=-82.100988
export PX4_HOME_LAT=45.3171
export PX4_HOME_LON=-120.9923
export PX4_HOME_ALT=1000
cd Firmware
#make px4_sitl gazebo 
make px4_sitl jmavsim
#mavproxy.py --master=udp:localhost:14550 --out=udp:localhost:14551 --out=udp:localhost:14552 --map --console

#make px4_sitl gazebo_plane
