#!/bin/bash
set -e
set -x
sudo apt install cmake libvecmath-java openjdk-8-jre openjdk-8-jdk
pip3 install --user empy
pip3 install --user jinja2
pip3 install --user pyros-genmsg
pip3 install --user packaging
pip3 install --user toml
pip3 install --user numpy

if [ ! -d "Firmware" ] 
then
    git clone https://github.com/PX4/Firmware.git --recursive
fi

#sudo apt-get install python3-dev python3-opencv python3-wxgtk3.0 python3-pip python3-matplotlib python3-pygame python3-lxml python3-yaml
#MAVPROXY
#some of the packages fail...
#sudo apt install libgtk-3-dev libwebkitgtk-dev libwebkitgtk-3.0-dev libgstreamer-gl1.0-0 freeglut3 freeglut3-dev python-gst-1.0 python3-gst-1.0 libglib2.0-dev ubuntu-restricted-extras libgstreamer-plugins-base1.0-dev
#broken
#sudo apt search python3-wx
#needed for the map
sudo apt-get install python3-opencv
#not tested
#sudo apt-get install python3-wxgtk4.0 python3-wxgtk-webview4.0 python3-wxgtk-media4.0
pip3 install --user wxpython
pip3 install --user MAVProxy

